server:
  port: 9000

spring:
  application:
    name: employee-manage-system
  token:
    name: employee-token

#redis配置
  redis:
    host: 121.196.223.21
    port: 6379
    password: 445221
    lettuce:
      pool:
        max-idle: 30
        max-active: 8
        max-wait: 10000ms
        min-idle: 10
    token:
      prefix: "employee-manage-system"
  main:
    allow-bean-definition-overriding: true

#sharding读写分离配置
sharding:
  jdbc:
    datasource:
      names: master,slave0,slave1
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://121.196.223.21:3306/employee_dev?serverTimezone=GMT%2B8
        username: root
        password: 445221
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://121.196.223.21:3306/employee_dev?serverTimezone=GMT%2B8
        username: root
        password: 445221
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://121.196.223.21:3306/employee_dev?serverTimezone=GMT%2B8
        username: root
        password: 445221
    config:
      masterslave:
        master-data-source-name: master
        slave-data-source-names: slave0,slave1
        load-balance-algorithm-type: round_robin
        name: datasource

#mybatis配置
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*Mapper.xml

#shiro配置
shiro:
  login-url: "/user/login"
  logout-url: "/user/logout"
  index-url: "/"
  all-url: "/**"
  webjars-url: "/webjars/**"
  swagger-ui-url: "/swagger-ui.html"
  swagger-resource-url: "/swagger-resources/**"
  api-docs-url: "/v2/api-docs"
  authc-token: "authcToken"
  permission: "permisssion"
  anon: "anon"

#swagger配置
swagger:
  api:
    package: cn.edu.scau.employee.controller

#端点监控
management:
  endpoints:
    web:
      exposure:
        include: "*"

